# fly.toml app configuration file generated for replicant-site-broken-pine-1879 on 2024-03-29T19:19:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'replicant-site'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  max_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
