name: platform_docs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/platform_docs.yaml
      - apps/platform/**

env:
  ELIXIR_VERSION: ${{ vars.ELIXIR_VERSION }}
  OTP_VERSION: ${{ vars.OTP_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/platform
    steps:
      - uses: actions/checkout@v3

      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ env.ELIXIR_VERSION }}
          otp-version: ${{ env.OTP_VERSION }}

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v3
        id: mix-cache
        with:
          path: deps
          key: ${{ runner.os }}-${{ env.OTP_VERSION }}-${{ env.ELIXIR_VERSION }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Install Mix Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
        if: steps.mix-cache.outputs.cache-hit != 'true'

      - name: Generate docs
        run: mix docs
  
      - name: Upload docs
        uses: actions/upload-pages-artifact@v1
        with:
          path: doc

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    defaults:
      run:
        working-directory: apps/platform
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
