name: site_deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/site_deploy.yaml
      - apps/site/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/site
    steps:
      - uses: actions/checkout@v3
    
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.TOKEN_FLY }}
