name: worker_cli_release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

env: 
  BUN_VERSION: ${{ vars.BUN_VERSION }}
  NODE_VERSION: ${{ vars.NODE_VERSION }}

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/worker_cli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Install sdk dependencies
        run: npm install
        working-directory: apps/worker_sdk

      - name: Build JS sdk
        run: npm run build
        working-directory: apps/worker_sdk

      - name: Install dependencies
        run: npm install

      - name: Build worker cli
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GH }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./apps/worker_cli
          push: true
          tags: |
            ghcr.io/replicantzk/worker:latest
            ghcr.io/replicantzk/worker:${{ github.ref_name }}
